const cardInfo = [
    {
      id: 1,
      name: 'Education Plans',
      text:
          'Kids Galaxy provides effectual and attractive education plans that emphasize on interaction, activities, learning opportunities, health and safety routines and more.',
          image: 'images/pencil.svg',
          image2: 'images/services icons/education-plans/excellence.svg',
      image3: 'images/services icons/education-plans/strategy.svg',
      image4: 'images/services icons/education-plans/growth.svg',
          nextSect: 'Operations Management',
          firstHeading: 'Achieve Academic Excellence',
          firstSub: 'Kids Galaxy assures maintenance of adequate inputs, high quality of education, thorough research and analysis, detailed yet quick assessment preparations, distributing appropriate time, ongoing evaluation, secure and oragnised system and more.',
          secondHeading: 'Plans for every need',
          secondSub: 'After extensive research and analysis, kids galaxy provides detailed plans for every step. Academic Plans, Instructional Plans, Administrative Plans, Assessment Plans.',
          thirdHeading: 'Benefits',
          thirdSub: "A sustainable education plan is the first step towards the school's progress. Well-thought-out planning is the only way to ensure students' overall growth.",
        },
        {
        id: 2,
    name: 'Operations Management',
    text:
          "Facilitate operations by assembling calculated and efficient management techniques provided by Kids Galaxy's well researched and experienced team.",
          image: 'images/administration.svg',
          image2: 'images/services icons/ops-mgmt/optimization.svg',
      image3: 'images/services icons/ops-mgmt/technical-support.svg',
      image4: 'images/services icons/ops-mgmt/growth.svg',
          nextSect: 'HR Management',
          firstHeading: 'Optimize organization results',
          firstSub: 'Kids Galaxy makes management of the daily operations in your school hassle free by reducing the amount of work load and the challenges that come with it.',
          secondHeading: 'Support from operations gurus',
          secondSub: 'Kids Galaxy specialises in a wide range of operations which includes developing robust financial management systems, incorporating asset management, establishing budgeting and reporting, documentation and record maintenance.',
          thirdHeading: 'Benefits',
          thirdSub: "Kids Galaxy's operations management techniques will allow you to see improvements in areas such as finance, curriculum, daily activities, and all major functions of your oraanization.",
        },
        {
          id: 3,
    name: 'HR Management',
    text:
          "Bring in passionate and committed employees, collaborate with all departments, and develop the organization's culture and valueScaleCorrection.",
          image: 'images/human-resources.svg',
          image2: 'images/services icons/hr-mgmt/research.svg',
      image3: 'images/services icons/hr-mgmt/career.svg',
      image4: 'images/services icons/hr-mgmt/growth.svg',
          nextSect: 'Academic Calendar',
          firstHeading: 'Find skilled and efficient staff',
          firstSub: 'Kids Galaxy develops tailer-made employee hiring strategies based on your requirements in order to provide you with skilled and efficient employees who are a perfect fit for the role.',
          secondHeading: "Evolve your school's system",
          secondSub: 'Kids Galaxy assists in assessing job efficiency, desgining work trackers and developing performance enhancement strategies, allowing employees to feel more motivated at work.',
          thirdHeading: 'Benefits',
          thirdSub: "Build a positive work environment, track and analyze employee performance, hassle free recruitment of Teachers, Clerks, Accountants, Coordinators, Administrators, Vice Principal, Principal and all types of skillful staff according to your needs.",
        },
        {
          id: 4,
          name: 'Academic Calendar',
          text:
            'Create a well-designed schedule to stay aligned to your goals',
            image: 'images/dates.svg',
            image2: '',
      image3: '',
      image4: '',
            nextSect: "Teacher's Training",
            firstHeading: 'Achieve Academic Excellence',
      firstSub: 'Kids Galaxy assures maintenance of adequate inputs, high quality of education, thorough research and analysis, detailed yet quick assessment preparations, distributing appropriate time, ongoing evaluation, secure and oragnised system and more.',
      secondHeading: 'Plans for every need',
      secondSub: 'After extensive research and analysis, kids galaxy provides detailed plans for every step. Academic Plans, Instructional Plans, Administrative Plans, Assessment Plans.',
      thirdHeading: 'Benefits',
      thirdSub: "A sustainable education plan is the first step towards the school's progress. Well-thought-out planning is the only way to ensure students' overall growth.",
        },
        {
          id: 5,
          name: "Teachers' Training",
          text:
          'Increase competency of teachers to mentor students more professionally',
          image: 'images/boss.svg',
          nextSect: 'School Structure',
          firstHeading: 'Achieve Academic Excellence',
      firstSub: 'Kids Galaxy assures maintenance of adequate inputs, high quality of education, thorough research and analysis, detailed yet quick assessment preparations, distributing appropriate time, ongoing evaluation, secure and oragnised system and more.',
      secondHeading: 'Plans for every need',
      secondSub: 'After extensive research and analysis, kids galaxy provides detailed plans for every step. Academic Plans, Instructional Plans, Administrative Plans, Assessment Plans.',
      thirdHeading: 'Benefits',
      thirdSub: "A sustainable education plan is the first step towards the school's progress. Well-thought-out planning is the only way to ensure students' overall growth.",
        },
        {
            id: 6,
            name: 'School Structure',
            text:
            'Revamp your school in a new, up-to-date style',
            image: 'images/university.svg',
            image2: '',
      image3: '',
      image4: '',
            nextSect: 'School Marketing',
            firstHeading: 'Achieve Academic Excellence',
      firstSub: 'Kids Galaxy assures maintenance of adequate inputs, high quality of education, thorough research and analysis, detailed yet quick assessment preparations, distributing appropriate time, ongoing evaluation, secure and oragnised system and more.',
      secondHeading: 'Plans for every need',
      secondSub: 'After extensive research and analysis, kids galaxy provides detailed plans for every step. Academic Plans, Instructional Plans, Administrative Plans, Assessment Plans.',
      thirdHeading: 'Benefits',
      thirdSub: "A sustainable education plan is the first step towards the school's progress. Well-thought-out planning is the only way to ensure students' overall growth.",
          },
          {
            id: 7,
            name: 'School Marketing',
            text:
        "Plan, strategize, and execute tailor-made marketing campaigns designed by Kids Galaxy's marketing experts to expand your school's reach.",
        image: 'images/megaphone.svg',
        image2: 'images/services icons/school-marketing/increase.svg',
      image3: 'images/services icons/school-marketing/bar-chart.svg',
      image4: 'images/services icons/school-marketing/growth.svg',
        nextSect: 'Event Ideation',
        firstHeading: "Enhance your school's recognition",
        firstSub: "Kids Galaxy conducts thorough market research and analysis to identify oppotunities that will increase your school's popularity and identity",
        secondHeading: 'Take the leap to the top!',
        secondSub: 'At Kids Galaxy, we create precise and goal-oriented marketing campaigns that help in generating admission enquiries, converting them into admission, data collection, etc.',
        thirdHeading: 'Benefits',
        thirdSub: "Kids Galaxy's marketing strategies will help you build your school's brand identity, admission retention, increased revenue, higher conversion rates of admissions, etc.",
            },
            {
                id: 8,
                name: 'Event Ideation',
                text:
                  'Organize eye-catching events to bask-in renown',
                  image: 'images/calendar.svg',
                  image2: '',
      image3: '',
      image4: '',
                  nextSect: 'Education Plans',
                  firstHeading: 'Achieve Academic Excellence',
      firstSub: 'Kids Galaxy assures maintenance of adequate inputs, high quality of education, thorough research and analysis, detailed yet quick assessment preparations, distributing appropriate time, ongoing evaluation, secure and oragnised system and more.',
      secondHeading: 'Plans for every need',
      secondSub: 'After extensive research and analysis, kids galaxy provides detailed plans for every step. Academic Plans, Instructional Plans, Administrative Plans, Assessment Plans.',
      thirdHeading: 'Benefits',
      thirdSub: "A sustainable education plan is the first step towards the school's progress. Well-thought-out planning is the only way to ensure students' overall growth.",
              },
    ];

export default cardInfo;