/* Data that is used on What We Do Mobile Page */
const cardInfo = [
    {
        id: 1,
        name: 'School Structure',
        text:
        'Revamp your school in a new, up-to-date style',
        image: 'images/university.svg',
        link: '/services',
        linkText: 'Know More',
        height: '17vh',
        width: '40vw',
        padding: '',
        cardId: 1,
        name2: 'School Marketing',
        text2:
          "Calibrated marketing strategies to enhance your school's recognition",
          image2: 'images/megaphone.svg',
          link2: '/services',
          linkText2: 'Know More',
          height2: '17vh',
          width2: '40vw',
          padding2: '',
          cardId2: 2,
        },
        {
            id: 2,
            name: 'Event Ideation',
            text:
              'Organize eye-catching events to bask-in renown',
              image: 'images/calendar.svg',
              link: '/services',
              linkText: 'Know More',
              height: '17vh',
              width: '40vw',
              padding: '',
              cardId: 3,
            name2: 'Education Plans',
            text2:
              'Design well-thought-out plans to achieve academic excellence',
              image2: 'images/pencil.svg',
              link2: '/services',
              linkText2: 'Know More',
              height2: '17vh',
              width2: '40vw',
              cardId2: 4,
              padding2: '',
            },
            {
                id: 3,
                name: 'Ops Management',
                text:
                  'Efficient management methods for optimised organizational results',
                  image: 'images/administration.svg',
                  link: '/services',
                  linkText: 'Know More',
                  height: '17vh',
                  width: '40vw',
                  padding: '',
                  cardId: 5,
                name2: 'HR Management',
                text2:
                  'Make your workforce skilled and find efficient staff',
                  image2: 'images/human-resources.svg',
                  link2: '/services',
                  linkText2: 'Know More',
                  height2: '17vh',
                  width2: '40vw',
                  padding2: '',
                  cardId2: 6,
                },
                {
                    id: 4,
                    name: 'Academic Calendar',
                    text:
                      'Create a well-designed schedule to stay aligned to your goals',
                      image: 'images/dates.svg',
                      link: '/services',
                      linkText: 'Know More',
                      height: '17vh',
                      width: '40vw',
                      padding: '',
                      cardId: 7,
                    name2: "Teachers' Training",
                    text2:
                      'Increase competency of teachers to mentor students more professionally',
                      image2: 'images/boss.svg',
                      link2: '/services',
                      linkText2: 'Know More',
                      height2: '17vh',
                      width2: '40vw',
                      padding2: '',
                      cardId2: 8,
                    },
  ];
  
  export default cardInfo;